version: '3'

services:
  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    container_name: cube-demo-mysql
    environment:
        MYSQL_ROOT_PASSWORD: cubedemo
        MYSQL_DATABASE: cube_demo
        MYSQL_USER: cubedemo
        MYSQL_PASSWORD: cubedemo
    networks:
      - cubedemo
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - cubedemo

networks:
  cubedemo:
    external: true
