version: '3'

services:
  db:
    image: mysql/mysql-server
    ports:
    - "3306:3306"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
